// Browser-side glue: run the export pipeline and download the resulting artifact. This is the single
// helper every export button calls — screens never touch an emitter or the Packer directly. It returns
// the full ExportResult so a caller that cares (the Manuscript screen) can surface the manifest /
// preflight report and honor a submission-safe block.
//
// Manifest policy (resolved, not ambiguous): a manifest is ALWAYS generated by the pipeline, but only an
// ARCHIVAL export writes it to disk. Full-manuscript exports (the Manuscript screen) pass `archival: true`
// and download a `<stem>.manifest.json` provenance sidecar next to the artifact. Fragment exports (a
// single scene, one chapter, a packet's drafted scene) are NON-ARCHIVAL proof exports: they omit
// `archival`, so no sidecar is written — the manifest still exists on the returned result if the caller
// wants it, but a throwaway proof of one scene should not litter the user's downloads with provenance
// files. Fragment exports also pass `override` so a submission-safe preflight never gates a proof.

import type { ManuscriptOut } from "../api/types";
import {
  docxFilename,
  manifestFilename,
  markdownFilename,
  saveDocx,
  saveManifest,
  saveMarkdown,
} from "../lib/docx";
import { runExport, type ExportResult } from "./pipeline";
import type { ExportPreset } from "./presets";

export interface ExportAndSaveOptions {
  preset: ExportPreset;
  /** Filename stem (no extension) — the pipeline picks .docx/.md from the preset's emitter. */
  filenameStem: string;
  author?: string | null;
  draft?: boolean;
  /** Reader-DOCX title-page descriptor (mode line / fragment label). */
  renderSubtitle?: string;
  /** Bypass a submission-safe preflight block (proofing exports pass true). */
  override?: boolean;
  /** Archival export: also download a `<stem>.manifest.json` provenance sidecar. Full-book exports set
   *  this; fragment/proof exports leave it false. */
  archival?: boolean;
}

/**
 * Run the pipeline and, if an artifact was produced (i.e. preflight did not block), download it — plus a
 * manifest sidecar when `archival`. Returns the ExportResult either way so the caller can inspect
 * `preflight`/`manifest`/`artifact` (e.g. to surface a submission-safe block).
 */
export async function exportAndSave(
  ms: ManuscriptOut,
  opts: ExportAndSaveOptions,
): Promise<ExportResult> {
  const result = runExport(ms, opts.preset, {
    author: opts.author,
    draft: opts.draft,
    renderSubtitle: opts.renderSubtitle,
    override: opts.override,
    exportedAt: new Date().toISOString(),
  });
  const art = result.artifact;
  if (art?.kind === "markdown") saveMarkdown(art.content, markdownFilename(opts.filenameStem));
  else if (art?.kind === "docx") await saveDocx(art.doc, docxFilename(opts.filenameStem));
  // Sidecar only for archival exports that actually produced an artifact (a blocked export writes
  // nothing — the block is surfaced to the caller via the returned preflight report instead).
  if (art && opts.archival) saveManifest(result.manifest, manifestFilename(opts.filenameStem));
  return result;
}
