"""Seed the forward-drift baseline by reflecting a LIVE database's columns.

    uv run python scripts/snapshot_schema.py --database-url postgresql://user:pass@prod-host/dominion
    # or, taking the URL from the environment:
    DOMINION_DATABASE_URL=postgresql://... uv run python scripts/snapshot_schema.py

Reads `information_schema.columns` from the connected DB (public schema) into
`{table_name: sorted([column_names])}` and writes `tests/schema_baseline.json` with a metadata
header (source DB — password redacted, git commit, UTC generation time, and a LOUD warning).
It reflects the LIVE database, so it does NOT import the ORM / `Base.metadata` — the whole point is
to capture what the real DB actually has, independent of what the models currently declare.

============================================================================================
 !!! RUN THIS ONLY AGAINST A PROD-EQUIVALENT (post-real-deploy) DATABASE. NEVER a throwaway  !!!
 !!! `create_all` test DB.                                                                    !!!

 `create_all` builds EVERY current model column on a fresh DB, so a baseline taken from a test
 DB would already contain any forgotten-ALTER column and would bake that drift in as "fine" —
 rubber-stamping the exact bug tests/test_migration_forward_drift.py exists to catch. The
 baseline must reflect a database whose columns were provisioned by real deploys applying
 `apply_lightweight_migrations`, i.e. production or a faithful clone of it.
============================================================================================
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

from sqlalchemy import text
from sqlalchemy.engine import make_url
from sqlalchemy.ext.asyncio import create_async_engine

_REPO_ROOT = Path(__file__).resolve().parent.parent
_BASELINE_PATH = _REPO_ROOT / "tests" / "schema_baseline.json"

_LOUD_WARNING = (
    "GENERATED by scripts/snapshot_schema.py. This MUST be seeded from a PROD-EQUIVALENT "
    "(post-real-deploy) database, NEVER a throwaway create_all test DB -- a create_all baseline "
    "would bake any forgotten-ALTER drift in as 'fine' and defeat the forward-drift gate. "
    "Re-seed after every real deploy that changes the live schema."
)


def _to_asyncpg(url: str) -> str:
    """Normalize a postgres URL to the asyncpg driver scheme (mirrors shared/config._to_asyncpg)."""
    if url.startswith("postgresql+asyncpg://"):
        return url
    for scheme in ("postgresql://", "postgres://"):
        if url.startswith(scheme):
            return "postgresql+asyncpg://" + url[len(scheme) :]
    return url


def _resolve_url(cli_url: str | None) -> str:
    """--database-url wins, then $DOMINION_DATABASE_URL, then $DOMINION_TEST_DATABASE_URL."""
    url = cli_url or os.environ.get("DOMINION_DATABASE_URL") or os.environ.get("DOMINION_TEST_DATABASE_URL")
    if not url:
        raise SystemExit(
            "no database URL: pass --database-url or set DOMINION_DATABASE_URL / DOMINION_TEST_DATABASE_URL"
        )
    return _to_asyncpg(url)


def _git_commit() -> str:
    try:
        out = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=_REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        )
        return out.stdout.strip() or "unknown"
    except Exception:
        return "unknown"


def _redacted(url: str) -> str:
    """host/port/db with the password masked — safe to commit into the baseline header."""
    try:
        return make_url(url).render_as_string(hide_password=True)
    except Exception:
        return "unparseable"


async def _reflect_columns(url: str) -> dict[str, list[str]]:
    """{table_name: sorted([column_names])} from information_schema.columns (public schema)."""
    engine = create_async_engine(url)
    try:
        async with engine.connect() as conn:
            rows = (
                await conn.execute(
                    text(
                        "SELECT table_name, column_name FROM information_schema.columns "
                        "WHERE table_schema = 'public' ORDER BY table_name, column_name"
                    )
                )
            ).all()
    finally:
        # Close the pool inside the loop so the process exits cleanly (mirrors scripts/init_db.py).
        await engine.dispose()

    tables: dict[str, list[str]] = {}
    for table_name, column_name in rows:
        tables.setdefault(table_name, []).append(column_name)
    return {t: sorted(cols) for t, cols in sorted(tables.items())}


async def main() -> int:
    ap = argparse.ArgumentParser(description="Seed tests/schema_baseline.json from a prod-equivalent DB.")
    ap.add_argument(
        "--database-url",
        default=None,
        help="DB URL to reflect; defaults to $DOMINION_DATABASE_URL then $DOMINION_TEST_DATABASE_URL",
    )
    args = ap.parse_args()

    url = _resolve_url(args.database_url)
    redacted = _redacted(url)

    # Loud reminder to stderr — the operator, not the script, guarantees this is prod-equivalent.
    print("=" * 88, file=sys.stderr)
    print(f"[snapshot] reflecting {redacted}", file=sys.stderr)
    print("[snapshot] " + _LOUD_WARNING, file=sys.stderr)
    try:
        dbname = make_url(url).database or ""
    except Exception:
        dbname = ""
    if dbname.endswith("_test") or "test" in dbname:
        print(
            f"[snapshot] WARNING: database name {dbname!r} looks like a TEST DB. If this is a throwaway "
            "create_all DB, do NOT commit the result — see this script's docstring.",
            file=sys.stderr,
        )
    print("=" * 88, file=sys.stderr)

    tables = await _reflect_columns(url)

    baseline = {
        "__WARNING__": _LOUD_WARNING,
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "git_commit": _git_commit(),
        "source_database": redacted,
        "tables": tables,
    }

    _BASELINE_PATH.write_text(json.dumps(baseline, indent=2, sort_keys=False) + "\n", encoding="utf-8")
    print(f"[snapshot] wrote {_BASELINE_PATH} ({len(tables)} tables)")
    print("[snapshot] REVIEW before committing: confirm the source DB was prod-equivalent, not create_all.")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
