"""Sectioned ScenePacket Author — the concurrent replacement for the monolithic author.

The contract JSON is large and the author call is output-bound (~12.5s per 1k output tokens, measured),
so one monolithic call emits ~6k tokens and takes >50s every time. Output generation is sequential
WITHIN a request but parallel ACROSS requests, so this module splits the contract into ~5 SECTION calls
that each emit a disjoint slice — priming one shared cached prefix, then running the rest concurrently —
and merges the slices server-side back into the exact same body shape `parse.valid_scene_packet_body`
and the rest of the system already expect.

Split along dependency seams, not arbitrarily: the knowledge cluster (known_before / learned_during /
must_remain_hidden / pov_permissions) partitions ONE fact-space — a fact lives in exactly one bucket —
so those four fields stay in a SINGLE call to keep them coherent (splitting them manufactures the
reader/POV-knowledge contradictions QA would then block on). That knowledge section is the latency floor.

Fail-closed, like the monolithic author: any section that can't produce its slice (truncated /
unparseable / missing its keys) is retried ONCE escalated to the fallback model with headroom; only the
FAILED section reruns, never the whole packet. If a section still can't, the whole derive blocks with a
reason naming the section — the merged body never ships partial contract sections.

Concurrency is bounded by a process-global semaphore (settings.scene_packet_max_inflight_llm) so a wide
chapter's scenes×sections fan-out can't spike Anthropic's rate limits and trigger the 429 backoff that
would eat the latency win.
"""

from __future__ import annotations

import asyncio
from dataclasses import dataclass
from typing import Any

import structlog

from dominion.shared.config import settings
from dominion.workers import llm, telemetry
from dominion.workers.budget import TokenBudget, Usage
from dominion.workers.llm import CachedPrefixBlock, estimate_tokens
from dominion.workers.scene_packet.author import (
    _SYSTEM,
    CLAIM_SOURCES_SCHEMA_HINT,
    ScenePacketAuthorError,
    build_prefix,
    build_scene_context,
)
from dominion.workers.scene_packet.parse import extract_object, valid_scene_packet_body

log = structlog.get_logger()


@dataclass(frozen=True)
class _Section:
    """One slice of the contract: the top-level keys it owns, the schema subset shown to the model, and
    its token cap. `name` is stamped into the system prompt so the call site (and tests) can tell the
    section calls apart.

    `optional_keys` are kept in the merge if the model emits them but are NOT required for the section to
    pass — used for additive, nice-to-have output (e.g. claim_sources provenance) that must never
    fail-close a whole packet just because the model omitted it."""

    name: str
    keys: tuple[str, ...]
    schema_hint: str
    max_tokens: int
    optional_keys: tuple[str, ...] = ()
    # Headroom for an escalated retry that was cut off mid-object. Per-section (not one global floor) so a
    # dense section gets more room than a list-of-strings one — e.g. reviewer_instructions (six lanes of
    # bullets) needs more than phrases_to_avoid_echoing. Only applied when the first attempt truncated.
    fallback_floor: int = 6000


# The knowledge cluster is one section ON PURPOSE — its four fields partition a single fact-space and
# must stay mutually consistent. The rest split freely. word_budget is NOT a section: it is stamped
# server-side from the deterministic planner, never generated by the model.
_SECTIONS: tuple[_Section, ...] = (
    _Section(
        name="knowledge",
        keys=("known_before_scene", "learned_during_scene", "must_remain_hidden", "pov_permissions"),
        schema_hint=(
            "{\n"
            '  "known_before_scene": {"reader": [str], "pov": [str], "omniscient_author": [str]},\n'
            '  "learned_during_scene": {"reader_must_learn": [str], "reader_may_learn": [str], '
            '"reader_may_infer_only": [str]},\n'
            '  "must_remain_hidden": {"reader": [str], "pov": [str], "all_surface_prose": [str]},\n'
            '  "pov_permissions": {"may_notice": [str], "may_infer": [str], "must_not_know": [str], '
            '"may_be_wrong_about": [str]},\n' + CLAIM_SOURCES_SCHEMA_HINT + "}"
        ),
        # claim_sources cites the [C1] handles on the supplied canon snippets so a knowledge item traces
        # back to its source. Optional: a missing citation must not block the packet, so it is NOT in keys.
        optional_keys=("claim_sources",),
        max_tokens=4500,
        fallback_floor=8000,
    ),
    _Section(
        name="mysteries",
        keys=("intentional_mysteries", "reviewer_false_positive_traps"),
        schema_hint=(
            "{\n"
            '  "intentional_mysteries": [{"mystery": str, "desired_reader_effect": str, '
            '"do_not_explain": true}],\n'
            '  "reviewer_false_positive_traps": [str]\n'
            "}"
        ),
        max_tokens=2000,
        fallback_floor=6000,
    ),
    _Section(
        name="shape",
        keys=(
            "scene_no",
            "scene_job",
            "scene_type",
            "chapter_position",
            "required_beats",
            "forbidden_beats",
            "exit_state",
            "tone_pressure",
        ),
        schema_hint=(
            "{\n"
            '  "scene_no": int, "scene_job": str, "scene_type": str,\n'
            '  "chapter_position": "opening|middle|climax|aftermath|bridge",\n'
            '  "required_beats": [str], "forbidden_beats": [str], "exit_state": str, "tone_pressure": str\n'
            "}"
        ),
        max_tokens=2000,
        fallback_floor=6000,
    ),
    _Section(
        name="reviewer",
        keys=("reviewer_instructions",),
        schema_hint=(
            "{\n"
            '  "reviewer_instructions": {"continuity": [str], "pacing": [str], "dialogue": [str], '
            '"combat": [str], "sensory": [str], "voice": [str]}\n'
            "}"
        ),
        max_tokens=2000,
        fallback_floor=7000,
    ),
    _Section(
        name="phrases",
        keys=("phrases_to_avoid_echoing",),
        schema_hint='{\n  "phrases_to_avoid_echoing": [str]\n}',
        max_tokens=1200,
        fallback_floor=4000,
    ),
)

# A repair pass reformats a present-but-malformed slice (NOT a truncation) into valid JSON before the
# whole packet fails closed. It re-emits content that already fit, so it mirrors the section's own cap.
_SECTION_REPAIR_SYSTEM = (
    "You repair malformed JSON. You are given a model's raw output that failed to parse as the required "
    "JSON object, plus the exact schema it must match. Return ONE corrected JSON object with exactly the "
    "required keys — no prose, no code fences, no commentary. Preserve the original content; fix only "
    "structure/syntax. If a required key is genuinely absent, emit it with an empty value of the right type."
)

# One semaphore per running event loop (tests spin up a fresh loop per test), sized from settings on
# first use within that loop. Caps total in-flight SECTION calls across every scene of a derive.
_sems: dict[int, asyncio.Semaphore] = {}


def _inflight_sem() -> asyncio.Semaphore:
    loop = asyncio.get_running_loop()
    sem = _sems.get(id(loop))
    if sem is None:
        sem = asyncio.Semaphore(max(1, settings.scene_packet_max_inflight_llm))
        _sems[id(loop)] = sem
    return sem


def _section_directive(section: _Section) -> str:
    """The per-section instruction. It rides in the trailing (uncached) user block, NOT the system
    prompt, so every one of a scene's section calls shares ONE byte-identical cached prefix (the constant
    `_SYSTEM` + the shared scene context): the priming call WRITES that prefix once and the rest READ it
    at 0.1x. When this `[section:NAME]` marker lived in the SYSTEM prompt, each section was a DISTINCT
    cache prefix (Anthropic caches from the start of the request, system first), so the shared scene
    context was never read back — every section re-WROTE the full prefix at full budget weight and ~5
    writes summed past the per-scene ceiling (the 68k>60k blocks). The marker stays in the prompt for
    identifiability (and test routing), just BELOW the cache breakpoint where it can vary for free."""
    # Brevity is a hard constraint, not a style note: the author call is output-bound (~12.5s/1k tokens),
    # and the contract is machine-read, so terse lists keep each section well inside its token cap and out
    # of truncation territory. Reviewer instructions especially must be short imperative bullets, not prose.
    brevity = (
        "Be terse. JSON only — no prose, no paragraphs, no code fences. Each list: at most 6 items. "
        "Each string: one clause, <= 200 characters."
    )
    if section.name == "reviewer":
        brevity += " Each reviewer instruction is a concise, actionable imperative bullet — never a paragraph."
    return (
        f"[section:{section.name}] Emit ONLY the fields for this section — no other keys. "
        "Stay consistent with the chapter packet and the scene seed.\n"
        f"{brevity}\n\n"
        "Produce ONLY these fields as ONE JSON object (exactly these keys, nothing else):\n" + section.schema_hint
    )


def _section_ok(obj: Any, section: _Section) -> bool:
    """A usable section slice is a dict carrying every key the section owns."""
    return isinstance(obj, dict) and all(k in obj for k in section.keys)


def _slice(obj: dict[str, Any], section: _Section) -> dict[str, Any]:
    """Keep only the keys this section owns (required + optional), so a chatty model can't leak another
    section's fields into the merge (the next section is authoritative for its own keys)."""
    return {k: obj[k] for k in (*section.keys, *section.optional_keys) if k in obj}


def _why(obj: Any, usage: Usage, *, section: _Section, model: str, max_tokens: int) -> str:
    if usage.truncated:
        return (
            f"section '{section.name}' truncated at max_tokens={max_tokens} on {model} "
            f"({usage.output_tokens} output tokens)"
        )
    if not isinstance(obj, dict):
        return f"section '{section.name}' returned no parseable JSON object on {model}"
    missing = [k for k in section.keys if k not in obj]
    return f"section '{section.name}' missing required keys {missing} on {model}"


async def _repair_section(
    section: _Section,
    *,
    raw: str,
    model: str,
    budget: TokenBudget,
    failure_cause: str,
) -> Any:
    """Last-chance reformat of a present-but-malformed slice into valid JSON. Runs ONLY for a
    non-truncation parse failure (the keys are there, the structure is broken) on the fallback model, with
    its own tiny system prompt and no shared prefix — so it never poisons the author cache. Returns the
    parsed object (caller validates with `_section_ok`); never merges partial output."""
    user = (
        f"[section:{section.name}] Repair the malformed output below into ONE valid JSON object with "
        f"exactly these keys, preserving its content:\n{section.schema_hint}\n\nMALFORMED OUTPUT:\n{raw}"
    )
    async with _inflight_sem():
        with telemetry.call_metadata(
            section_name=section.name,
            section_attempt_kind="repair",
            section_max_tokens=section.max_tokens,
            section_failure_cause=failure_cause,
            fallback_attempt=True,
        ):
            repaired_raw, _usage = await llm.complete(
                model=model,
                system=_SECTION_REPAIR_SYSTEM,
                user=user,
                max_tokens=section.max_tokens,
                budget=budget,
                expect_cache=False,
                context_window_budget=settings.scene_packet_context_window_budget,
                context_sections={
                    "system": estimate_tokens(_SECTION_REPAIR_SYSTEM),
                    "repair_input": estimate_tokens(user),
                },
                input_budget=settings.scene_packet_author_prompt_budget,
            )
    return extract_object(repaired_raw)


async def _author_section(
    section: _Section,
    *,
    system: str,
    prefix_blocks: tuple[CachedPrefixBlock, ...],
    user: str,
    budget: TokenBudget,
    context_sections: dict[str, int],
) -> dict[str, Any]:
    """Produce one section's slice. Escalates primary -> fallback model (with extra headroom on a
    truncation), then -> one repair pass for a non-truncation parse failure, before failing the whole
    packet closed with a reason naming the section. Bounded by the global in-flight semaphore."""
    primary = settings.scene_packet_author_model
    fallback_model = (settings.scene_packet_author_fallback_model or "").strip()

    async def _attempt(
        model: str, max_tokens: int, *, attempt_kind: str, failure_cause: str | None = None
    ) -> tuple[str, Any, Usage]:
        async with _inflight_sem():
            with telemetry.call_metadata(
                section_name=section.name,
                section_primary_model=primary,
                section_fallback_model=fallback_model or None,
                section_attempt_kind=attempt_kind,
                section_max_tokens=max_tokens,
                section_failure_cause=failure_cause,
                # Keep the legacy key so telemetry_agg's `fallbacks` rollup still counts escalations.
                fallback_attempt=attempt_kind != "primary",
            ):
                raw, usage = await llm.complete(
                    model=model,
                    system=system,
                    user_prefix_blocks=prefix_blocks,
                    user=user,
                    max_tokens=max_tokens,
                    budget=budget,
                    context_window_budget=settings.scene_packet_context_window_budget,
                    context_sections=context_sections,
                    input_budget=settings.scene_packet_author_prompt_budget,
                )
        return raw, extract_object(raw), usage

    raw1, obj, usage = await _attempt(primary, section.max_tokens, attempt_kind="primary")
    if _section_ok(obj, section):
        return _slice(obj, section)

    first_cause = _why(obj, usage, section=section, model=primary, max_tokens=section.max_tokens)
    if not fallback_model or fallback_model == primary:
        raise ScenePacketAuthorError(f"{first_cause}; no fallback model configured")

    # Fallback (escalated). A genuine truncation gets the section's own headroom floor; a parse failure
    # keeps the same cap (more tokens won't fix malformed-but-complete output).
    fb_max = max(section.max_tokens, section.fallback_floor) if usage.truncated else section.max_tokens
    log.info("scene_packet.section_escalate", section=section.name, cause=first_cause, fallback=fallback_model)
    raw2, obj2, usage2 = await _attempt(fallback_model, fb_max, attempt_kind="fallback", failure_cause=first_cause)
    if _section_ok(obj2, section):
        return _slice(obj2, section)

    second_cause = _why(obj2, usage2, section=section, model=fallback_model, max_tokens=fb_max)
    # Repair ONLY a non-truncation parse failure: the content is present but malformed, so reformatting
    # the fallback's raw output can recover it. A truncation is missing content — repair can't invent it.
    if not usage2.truncated:
        log.info("scene_packet.section_repair", section=section.name, cause=second_cause)
        repaired = await _repair_section(
            section, raw=raw2, model=fallback_model, budget=budget, failure_cause=second_cause
        )
        if _section_ok(repaired, section):
            return _slice(repaired, section)
        raise ScenePacketAuthorError(
            f"{first_cause}; fallback {second_cause}; repair failed for section '{section.name}'"
        )
    raise ScenePacketAuthorError(f"{first_cause}; fallback {second_cause}")


def build_author_prefix_blocks(
    *,
    pov: str,
    chapter_packet_body: dict[str, Any],
    scene_seed: dict[str, Any],
    word_budget: dict[str, Any],
    prior_scene_summaries: list[str] | None = None,
    prior_exit_state: str | None = None,
    pov_summary: str | None = None,
    omniscient_summary: str | None = None,
    chapter_open_questions: dict[str, Any] | None = None,
    owner_snippets: list[str] | None = None,
    canon_snippets: list[str] | None = None,
) -> tuple[CachedPrefixBlock, CachedPrefixBlock]:
    chapter_shared_prefix = build_prefix(
        chapter_packet_body=chapter_packet_body,
        pov_summary=pov_summary,
        omniscient_summary=omniscient_summary,
        chapter_open_questions=chapter_open_questions,
    )
    scene_context_prefix = build_scene_context(
        pov=pov,
        scene_seed=scene_seed,
        word_budget=word_budget,
        prior_scene_summaries=prior_scene_summaries,
        prior_exit_state=prior_exit_state,
        owner_snippets=owner_snippets,
        canon_snippets=canon_snippets,
    )
    return (
        CachedPrefixBlock(name="chapter_shared_prefix", text=chapter_shared_prefix),
        CachedPrefixBlock(name="scene_context_prefix", text=scene_context_prefix),
    )


def context_sections_for_author_call(*, prefix_blocks: tuple[CachedPrefixBlock, ...], directive: str) -> dict[str, int]:
    sections = {"system": estimate_tokens(_SYSTEM)}
    sections.update({block.name: estimate_tokens(block.text) for block in prefix_blocks})
    sections["section_directive"] = estimate_tokens(directive)
    return sections


async def prime_author_shared_prefix(
    *,
    chapter_packet_body: dict[str, Any],
    pov_summary: str | None = None,
    omniscient_summary: str | None = None,
    chapter_open_questions: dict[str, Any] | None = None,
    budget: TokenBudget,
) -> None:
    """Prime the chapter-shared author prefix outside any scene-local work budget."""
    prefix = build_prefix(
        chapter_packet_body=chapter_packet_body,
        pov_summary=pov_summary,
        omniscient_summary=omniscient_summary,
        chapter_open_questions=chapter_open_questions,
    )
    user = "Acknowledge cache prime."
    await llm.complete(
        model=settings.scene_packet_author_model,
        system=_SYSTEM,
        user_prefix_blocks=(CachedPrefixBlock(name="chapter_shared_prefix", text=prefix),),
        user=user,
        max_tokens=16,
        budget=budget,
        context_window_budget=settings.scene_packet_context_window_budget,
        context_sections={
            "system": estimate_tokens(_SYSTEM),
            "chapter_shared_prefix": estimate_tokens(prefix),
            "prime_suffix": estimate_tokens(user),
        },
    )


async def author_scene_packet_sectioned(
    *,
    pov: str,
    chapter_packet_body: dict[str, Any],
    scene_seed: dict[str, Any],
    word_budget: dict[str, Any],
    prior_scene_summaries: list[str] | None = None,
    prior_exit_state: str | None = None,
    pov_summary: str | None = None,
    omniscient_summary: str | None = None,
    chapter_open_questions: dict[str, Any] | None = None,
    owner_snippets: list[str] | None = None,
    canon_snippets: list[str] | None = None,
    budget: TokenBudget,
) -> dict[str, Any]:
    """Build one ScenePacket body by fanning the contract into concurrent section calls and merging the
    slices. Same signature, same fail-closed contract, and same body shape as the monolithic
    `author.author_scene_packet` — the caller (`derive._author_then_qa`) treats them interchangeably.

    word_budget is stamped server-side so the model can never override the planner's numbers."""
    # The chapter-shared prefix is a cache breakpoint reused across scenes; the scene-context prefix is a
    # second breakpoint reused across this scene's section calls. Only the section directive varies.
    prefix_blocks = build_author_prefix_blocks(
        pov=pov,
        chapter_packet_body=chapter_packet_body,
        scene_seed=scene_seed,
        word_budget=word_budget,
        prior_scene_summaries=prior_scene_summaries,
        prior_exit_state=prior_exit_state,
        pov_summary=pov_summary,
        omniscient_summary=omniscient_summary,
        chapter_open_questions=chapter_open_questions,
        owner_snippets=owner_snippets,
        canon_snippets=canon_snippets,
    )

    async def _run(section: _Section) -> dict[str, Any]:
        directive = _section_directive(section)
        return await _author_section(
            section,
            system=_SYSTEM,
            prefix_blocks=prefix_blocks,
            user=directive,
            budget=budget,
            context_sections=context_sections_for_author_call(
                prefix_blocks=prefix_blocks,
                directive=directive,
            ),
        )

    # Prime only this scene's scene-context prefix before fanning out the remaining sections. The
    # chapter-shared prefix has already been primed by derive under the prefix-prime budget; this local
    # primer prevents every section from writing the scene seed/canon block at full weight. Any section
    # raising ScenePacketAuthorError fails the whole packet closed (the derive persists the reason).
    primer = min(_SECTIONS, key=lambda s: s.max_tokens)
    rest = [s for s in _SECTIONS if s is not primer]
    first = await _run(primer)
    others = await asyncio.gather(*(_run(s) for s in rest))
    slices = [first, *others]

    body: dict[str, Any] = {}
    for part in slices:
        body.update(part)
    body["word_budget"] = word_budget  # planner is authoritative, never the model

    if not valid_scene_packet_body(body):
        missing = [k for k in ("known_before_scene", "learned_during_scene", "word_budget") if k not in body]
        raise ScenePacketAuthorError(f"merged section body missing load-bearing keys {missing}")
    return body
