"""Sectioned ScenePacket Author — the concurrent replacement for the monolithic author.

The contract JSON is large and the author call is output-bound (~12.5s per 1k output tokens, measured),
so one monolithic call emits ~6k tokens and takes >50s every time. Output generation is sequential
WITHIN a request but parallel ACROSS requests, so this module splits the contract into ~5 SECTION calls
that each emit a disjoint slice, runs them concurrently, and merges the slices server-side back into the
exact same body shape `parse.valid_scene_packet_body` and the rest of the system already expect.

Split along dependency seams, not arbitrarily: the knowledge cluster (known_before / learned_during /
must_remain_hidden / pov_permissions) partitions ONE fact-space — a fact lives in exactly one bucket —
so those four fields stay in a SINGLE call to keep them coherent (splitting them manufactures the
reader/POV-knowledge contradictions QA would then block on). That knowledge section is the latency floor.

Fail-closed, like the monolithic author: any section that can't produce its slice (truncated /
unparseable / missing its keys) is retried ONCE escalated to the fallback model with headroom; only the
FAILED section reruns, never the whole packet. If a section still can't, the whole derive blocks with a
reason naming the section — the merged body never ships partial contract sections.

Concurrency is bounded by a process-global semaphore (settings.scene_packet_max_inflight_llm) so a wide
chapter's scenes×sections fan-out can't spike Anthropic's rate limits and trigger the 429 backoff that
would eat the latency win.
"""
from __future__ import annotations

import asyncio
from dataclasses import dataclass
from typing import Any

import structlog

from dominion.shared.config import settings
from dominion.workers import llm
from dominion.workers.budget import TokenBudget, Usage
from dominion.workers.scene_packet.author import (
    _SYSTEM,
    ScenePacketAuthorError,
    build_prefix,
    build_prompt,
)
from dominion.workers.scene_packet.parse import extract_object, valid_scene_packet_body

log = structlog.get_logger()


@dataclass(frozen=True)
class _Section:
    """One slice of the contract: the top-level keys it owns, the schema subset shown to the model, and
    its token cap. `name` is stamped into the system prompt so the call site (and tests) can tell the
    section calls apart."""
    name: str
    keys: tuple[str, ...]
    schema_hint: str
    max_tokens: int


# The knowledge cluster is one section ON PURPOSE — its four fields partition a single fact-space and
# must stay mutually consistent. The rest split freely. word_budget is NOT a section: it is stamped
# server-side from the deterministic planner, never generated by the model.
_SECTIONS: tuple[_Section, ...] = (
    _Section(
        name="knowledge",
        keys=("known_before_scene", "learned_during_scene", "must_remain_hidden", "pov_permissions"),
        schema_hint=(
            '{\n'
            '  "known_before_scene": {"reader": [str], "pov": [str], "omniscient_author": [str]},\n'
            '  "learned_during_scene": {"reader_must_learn": [str], "reader_may_learn": [str], '
            '"reader_may_infer_only": [str]},\n'
            '  "must_remain_hidden": {"reader": [str], "pov": [str], "all_surface_prose": [str]},\n'
            '  "pov_permissions": {"may_notice": [str], "may_infer": [str], "must_not_know": [str], '
            '"may_be_wrong_about": [str]}\n'
            '}'
        ),
        max_tokens=3500,
    ),
    _Section(
        name="mysteries",
        keys=("intentional_mysteries", "reviewer_false_positive_traps"),
        schema_hint=(
            '{\n'
            '  "intentional_mysteries": [{"mystery": str, "desired_reader_effect": str, '
            '"do_not_explain": true}],\n'
            '  "reviewer_false_positive_traps": [str]\n'
            '}'
        ),
        max_tokens=2000,
    ),
    _Section(
        name="shape",
        keys=("scene_no", "scene_job", "scene_type", "chapter_position",
              "required_beats", "forbidden_beats", "exit_state", "tone_pressure"),
        schema_hint=(
            '{\n'
            '  "scene_no": int, "scene_job": str, "scene_type": str,\n'
            '  "chapter_position": "opening|middle|climax|aftermath|bridge",\n'
            '  "required_beats": [str], "forbidden_beats": [str], "exit_state": str, "tone_pressure": str\n'
            '}'
        ),
        max_tokens=2000,
    ),
    _Section(
        name="reviewer",
        keys=("reviewer_instructions",),
        schema_hint=(
            '{\n'
            '  "reviewer_instructions": {"continuity": [str], "pacing": [str], "dialogue": [str], '
            '"combat": [str], "sensory": [str], "voice": [str]}\n'
            '}'
        ),
        max_tokens=2000,
    ),
    _Section(
        name="phrases",
        keys=("phrases_to_avoid_echoing",),
        schema_hint='{\n  "phrases_to_avoid_echoing": [str]\n}',
        max_tokens=1200,
    ),
)

# Headroom for a section's escalated retry when its first pass was cut off mid-object.
_SECTION_FALLBACK_FLOOR = 4000

# One semaphore per running event loop (tests spin up a fresh loop per test), sized from settings on
# first use within that loop. Caps total in-flight SECTION calls across every scene of a derive.
_sems: dict[int, asyncio.Semaphore] = {}


def _inflight_sem() -> asyncio.Semaphore:
    loop = asyncio.get_running_loop()
    sem = _sems.get(id(loop))
    if sem is None:
        sem = asyncio.Semaphore(max(1, settings.scene_packet_max_inflight_llm))
        _sems[id(loop)] = sem
    return sem


def _section_system(section: _Section) -> str:
    """The base author rules plus a directive to emit ONLY this section's fields. The `[section:NAME]`
    marker makes the call identifiable (and lets tests route a fake response per section)."""
    return (
        f"{_SYSTEM}\n\n[section:{section.name}] Emit ONLY the fields for this section — no other keys, "
        "no prose, no code fences. Stay consistent with the chapter packet and the scene seed."
    )


def _section_closing(section: _Section) -> str:
    return ("Produce ONLY these fields as ONE JSON object (exactly these keys, nothing else):\n"
            + section.schema_hint)


def _section_ok(obj: Any, section: _Section) -> bool:
    """A usable section slice is a dict carrying every key the section owns."""
    return isinstance(obj, dict) and all(k in obj for k in section.keys)


def _slice(obj: dict[str, Any], section: _Section) -> dict[str, Any]:
    """Keep only the keys this section owns, so a chatty model can't leak another section's fields into
    the merge (the next section is authoritative for its own keys)."""
    return {k: obj[k] for k in section.keys if k in obj}


def _why(obj: Any, usage: Usage, *, section: _Section, model: str, max_tokens: int) -> str:
    if usage.truncated:
        return (f"section '{section.name}' truncated at max_tokens={max_tokens} on {model} "
                f"({usage.output_tokens} output tokens)")
    if not isinstance(obj, dict):
        return f"section '{section.name}' returned no parseable JSON object on {model}"
    missing = [k for k in section.keys if k not in obj]
    return f"section '{section.name}' missing required keys {missing} on {model}"


async def _author_section(
    section: _Section, *, system: str, prefix: str, user: str, budget: TokenBudget
) -> dict[str, Any]:
    """Produce one section's slice. Retries ONCE escalated to the fallback model (with extra headroom on
    a truncation) before failing closed for the whole packet. Bounded by the global in-flight semaphore."""

    async def _attempt(model: str, max_tokens: int) -> tuple[Any, Usage]:
        async with _inflight_sem():
            raw, usage = await llm.complete(
                model=model, system=system, user_prefix=prefix, user=user,
                max_tokens=max_tokens, budget=budget,
            )
        return extract_object(raw), usage

    primary = settings.scene_packet_author_model
    obj, usage = await _attempt(primary, section.max_tokens)
    if _section_ok(obj, section):
        return _slice(obj, section)

    first_cause = _why(obj, usage, section=section, model=primary, max_tokens=section.max_tokens)
    fallback = (settings.scene_packet_author_fallback_model or "").strip()
    if not fallback or fallback == primary:
        raise ScenePacketAuthorError(f"{first_cause}; no fallback model configured")

    fb_max = max(section.max_tokens, _SECTION_FALLBACK_FLOOR) if usage.truncated else section.max_tokens
    log.info("scene_packet.section_escalate", section=section.name, cause=first_cause, fallback=fallback)
    obj2, usage2 = await _attempt(fallback, fb_max)
    if _section_ok(obj2, section):
        return _slice(obj2, section)
    raise ScenePacketAuthorError(
        f"{first_cause}; fallback {_why(obj2, usage2, section=section, model=fallback, max_tokens=fb_max)}"
    )


async def author_scene_packet_sectioned(
    *,
    pov: str,
    chapter_packet_body: dict[str, Any],
    scene_seed: dict[str, Any],
    word_budget: dict[str, Any],
    prior_scene_summaries: list[str] | None = None,
    prior_exit_state: str | None = None,
    pov_summary: str | None = None,
    omniscient_summary: str | None = None,
    owner_snippets: list[str] | None = None,
    canon_snippets: list[str] | None = None,
    budget: TokenBudget,
) -> dict[str, Any]:
    """Build one ScenePacket body by fanning the contract into concurrent section calls and merging the
    slices. Same signature, same fail-closed contract, and same body shape as the monolithic
    `author.author_scene_packet` — the caller (`derive._author_then_qa`) treats them interchangeably.

    word_budget is stamped server-side so the model can never override the planner's numbers."""
    prefix = build_prefix(
        chapter_packet_body=chapter_packet_body,
        pov_summary=pov_summary, omniscient_summary=omniscient_summary,
    )

    async def _run(section: _Section) -> dict[str, Any]:
        user = build_prompt(
            pov=pov, scene_seed=scene_seed, word_budget=word_budget,
            prior_scene_summaries=prior_scene_summaries, prior_exit_state=prior_exit_state,
            owner_snippets=owner_snippets, canon_snippets=canon_snippets,
            closing=_section_closing(section),
        )
        return await _author_section(
            section, system=_section_system(section), prefix=prefix, user=user, budget=budget
        )

    # Any section raising ScenePacketAuthorError fails the whole packet closed (gather re-raises the
    # first); the derive persists that reason as the scene's blocked_reason.
    slices = await asyncio.gather(*(_run(s) for s in _SECTIONS))

    body: dict[str, Any] = {}
    for part in slices:
        body.update(part)
    body["word_budget"] = word_budget  # planner is authoritative, never the model

    if not valid_scene_packet_body(body):
        missing = [k for k in ("known_before_scene", "learned_during_scene", "word_budget")
                   if k not in body]
        raise ScenePacketAuthorError(f"merged section body missing load-bearing keys {missing}")
    return body
